export {
  COUNTDOWN_START,
  COUNTDOWN_TICK_MS,
  createY2kCanvasState,
  countdownNumber,
  countdownProgress,
  DIGITS_FROM,
  DIGITS_TO,
  digitRollProgress,
  digitScrollPosition,
  buildNewsTickerText,
  NEWS_TICKER_HEADLINES,
  NEWS_TICKER_SPEED,
  PALETTE,
  panicLevel,
  PHASE_MS,
  renderY2kCanvas,
  rollDistance,
  spawnConfetti,
  spawnConfettiWave,
  CONFETTI_GRAVITY,
  CONFETTI_MAX_WAVES,
  CONFETTI_PER_WAVE,
  CONFETTI_WAVE_INTERVAL_MS,
  stepY2kCanvasState,
  type ConfettiParticle,
  type Y2kCanvasState,
  type Y2kPhase,
} from "./canvas";
