/** Canonical company / org ids and display names. */
export const COMPANIES: Record<string, { name: string }> = {
  adobe: { name: "Adobe" },
  alibaba: { name: "Alibaba" },
  amazon: { name: "Amazon" },
  amd: { name: "AMD" },
  anthropic: { name: "Anthropic" },
  anysphere: { name: "Anysphere" },
  "apache-software-foundation": { name: "Apache Software Foundation" },
  apple: { name: "Apple" },
  atlassian: { name: "Atlassian" },
  "bell-labs": { name: "Bell Labs" },
  cern: { name: "CERN" },
  deepseek: { name: "DeepSeek" },
  docker: { name: "Docker" },
  fsf: { name: "Free Software Foundation" },
  github: { name: "GitHub" },
  google: { name: "Google" },
  hashicorp: { name: "HashiCorp" },
  heroku: { name: "Heroku" },
  ibm: { name: "IBM" },
  ietf: { name: "IETF" },
  intel: { name: "Intel" },
  jetbrains: { name: "JetBrains" },
  macromedia: { name: "Macromedia" },
  meta: { name: "Meta" },
  microsoft: { name: "Microsoft" },
  moonshot: { name: "Moonshot AI" },
  mongodb: { name: "MongoDB" },
  mozilla: { name: "Mozilla" },
  netflix: { name: "Netflix" },
  netlify: { name: "Netlify" },
  netscape: { name: "Netscape" },
  nginx: { name: "Nginx" },
  nvidia: { name: "NVIDIA" },
  openai: { name: "OpenAI" },
  opera: { name: "Opera" },
  oracle: { name: "Oracle" },
  redis: { name: "Redis" },
  salesforce: { name: "Salesforce" },
  samsung: { name: "Samsung" },
  "sun-microsystems": { name: "Sun Microsystems" },
  tsmc: { name: "TSMC" },
  vercel: { name: "Vercel" },
  w3c: { name: "W3C" },
  xai: { name: "xAI" },
};

/**
 * Timeline tags that imply a company when present on an event.
 * Ambiguous tags (e.g. `webkit`) are omitted — use manual attributions instead.
 */
export const TAG_TO_COMPANY_ID: Record<string, string> = {
  actionscript: "adobe",
  adobe: "adobe",
  alibaba: "alibaba",
  anysphere: "anysphere",
  cursor: "anysphere",
  flash: "adobe",
  qwen: "alibaba",
  amazon: "amazon",
  aws: "amazon",
  amd: "amd",
  anthropic: "anthropic",
  claude: "anthropic",
  apache: "apache-software-foundation",
  apple: "apple",
  ios: "apple",
  iphone: "apple",
  macos: "apple",
  "objective-c": "apple",
  safari: "apple",
  swift: "apple",
  atlassian: "atlassian",
  bitbucket: "atlassian",
  "bell-labs": "bell-labs",
  cern: "cern",
  docker: "docker",
  container: "docker",
  deepseek: "deepseek",
  "free-software": "fsf",
  gnu: "fsf",
  github: "github",
  android: "google",
  angular: "google",
  angularjs: "google",
  chrome: "google",
  chromium: "google",
  dart: "google",
  deepmind: "google",
  flutter: "google",
  gemini: "google",
  go: "google",
  golang: "google",
  google: "google",
  kubernetes: "google",
  tensorflow: "google",
  hashicorp: "hashicorp",
  terraform: "hashicorp",
  vagrant: "hashicorp",
  heroku: "heroku",
  ibm: "ibm",
  ietf: "ietf",
  intel: "intel",
  jetbrains: "jetbrains",
  phpstorm: "jetbrains",
  pycharm: "jetbrains",
  webstorm: "jetbrains",
  kotlin: "jetbrains",
  facebook: "meta",
  graphql: "meta",
  kimi: "moonshot",
  meta: "meta",
  macromedia: "macromedia",
  dreamweaver: "macromedia",
  moonshot: "moonshot",
  react: "meta",
  aspnet: "microsoft",
  azure: "microsoft",
  csharp: "microsoft",
  dotnet: "microsoft",
  fsharp: "microsoft",
  iis: "microsoft",
  "internet-explorer": "microsoft",
  microsoft: "microsoft",
  nuget: "microsoft",
  powershell: "microsoft",
  typescript: "microsoft",
  "vb-net": "microsoft",
  "visual-basic": "microsoft",
  windows: "microsoft",
  xamarin: "microsoft",
  mongodb: "mongodb",
  firefox: "mozilla",
  mozilla: "mozilla",
  netflix: "netflix",
  netlify: "netlify",
  netscape: "netscape",
  nginx: "nginx",
  cuda: "nvidia",
  nvidia: "nvidia",
  chatgpt: "openai",
  gpt: "openai",
  openai: "openai",
  opera: "opera",
  oracle: "oracle",
  redis: "redis",
  salesforce: "salesforce",
  samsung: "samsung",
  java: "sun-microsystems",
  jvm: "sun-microsystems",
  sun: "sun-microsystems",
  tsmc: "tsmc",
  nextjs: "vercel",
  vercel: "vercel",
  w3c: "w3c",
  grok: "xai",
  xai: "xai",
};
