/** Shorter bubble-friendly titles keyed by event id. */
export const SHORT_BUBBLE_TITLES: Record<string, string> = {
  "anthropic-fable-abruptly-disable-quote": "Anthropic disables Fable 5 and Mythos 5",
  "ballmer-web-developers-chant": 'Ballmer: "Web developers!" chant',
  "altman-ai-goes-wrong": "Altman: AI can go quite wrong",
  "anthropic-fable-halt-deployments-quote": "Anthropic: halt model deployments",
  "huang-generative-ai-era-quote": "Huang: generative AI era",
  "dijkstra-goto-letter-quote": "Dijkstra: Go To considered harmful",
  "joy-most-smart-people-elsewhere": "Bill Joy: smartest people elsewhere",
  "anthropic-fable-serious-damage-quote": "Anthropic: Fable 5 misuse risk",
  "brooks-add-manpower-makes-later": "Brooks: adding people delays projects",
  "torvalds-reply-linux-obsolete": "Torvalds: Linux more portable than Minix",
  "guido-van-rossum-psf-founded": "Python Software Foundation founded",
  "ballmer-developers-chant": 'Ballmer: "Developers!" chant',
  "moore-components-doubling-quote": "Moore: chip density doubles yearly",
  "diffie-hellman-paper-published": "Diffie–Hellman cryptography paper",
  "chris-wanstrath-github-ceo-steps-down": "Chris Wanstrath steps down as CEO",
  "karen-sparck-jones-idf": "Karen Spärck Jones publishes IDF",
  "tony-hoare-csp-published": "Hoare publishes CSP",
  "john-von-neumann-architecture": "von Neumann stored-program architecture",
  "edsac-initial-orders": "EDSAC Initial Orders assembler",
  "grace-hopper-nanoseconds-lecture": "Grace Hopper nanosecond lecture",
  "ada-lovelace-analytical-engine-notes": "Ada Lovelace Analytical Engine notes",
  "rich-sutton-rl-textbook": "Sutton RL textbook published",
  "jack-kilby-integrated-circuit": "Kilby demonstrates first IC",
  "lynn-conway-vlsi-course": "Mead–Conway VLSI methodology",
  "richard-stallman-fsf-founded": "Richard Stallman founds FSF",
  "kurzweil-law-accelerating-returns": "Kurzweil: accelerating returns",
  "crockford-javascript-good-parts": "JavaScript: The Good Parts",
  "clifford-cocks-public-key": "Cocks invents RSA at GCHQ",
  "apple-ii-introduced": "Apple II introduced",
  "goldwasser-micali-zero-knowledge-published": "Zero-knowledge proofs published",
  "eric-raymond-cathedral-bazaar": "The Cathedral and the Bazaar",
  "sanfilippo-redis-maintainer-steps-down": "Sanfilippo steps down from Redis",
  "huang-ceo-math-quote": "Huang: more you buy, more you save",
  "amd-advancing-ai-2026": "AMD MI400 and Helios announced",
  "robert-noyce-integrated-circuit": "Noyce invents planar IC",
  "torvalds-talk-is-cheap": "Torvalds: Talk is cheap",
  "css-selectors-level-3-recommendation": "CSS Selectors Level 3 standard",
  "mcp-donated-to-linux-foundation": "MCP donated to Linux Foundation",
  "knuth-premature-optimization": "Knuth: premature optimization",
  "yann-lecun-lenet-published": "LeNet convolutional networks",
  "kent-beck-extreme-programming": "Extreme Programming Explained",
  "hinton-alexnet-imagenet-breakthrough": "AlexNet wins ImageNet",
  "geoffrey-hinton-google-departure": "Hinton leaves Google over AI risk",
};
